### ISSUE TITLE
predict function

### ISSUE THREAD

**Issue by ioannis12** [OpenDebates/openskill.py#2]
hello, 

congrats for your work! I was wondering if there is a predict function for the rankings?

greetings

**Comment by daegontaven** [comment]
> I was wondering if there is a predict function for the rankings?

There is no predict function. Can you elaborate more on what the function does? Is it supposed something that compares two or more `Rating` objects (or teams) and gives you probability of [winning/drawing](https://trueskill.org/#trueskill.TrueSkill.quality) like in trueskill python?

**Comment by ioannis12** [comment]
yes, exactly that

**Comment by daegontaven** [comment]
There is a snippet on calculating win probability for two teams [here](https://github.com/sublee/trueskill/issues/1#issuecomment-911618556). I'm sure it can be translated to use our models. However, I am not willing to create such a function unless it can successfully make predictions for the n-teams general case. If you have figured out how to do this for the general case, feel free to make a PR.

**Comment by ioannis12** [comment]
thanks for the tip! Do you think one predict function would work the same for every model?

**Comment by daegontaven** [comment]
One predict function would be preferable where you pass in the model as an argument to it. One thing to note is that Bradley-Terry and Plackett-Luce models are over a logistic distribution while Thurstone-Mosteller is over a normal distribution.

**Comment by philihp** [comment]
If you make an n-team, n-player prediction function, I'd love to include it on the Javascript library as well! It is a common ask.

I think a good criteria for such a thing should be among the teams A, B, C, if we predict A will win 50% of the time, B will win 40%, and C wins 10% of the time, then we can monte-carlo actual results with those actual results, and the resulting ratings should have similar `mu`.
