### ISSUE TITLE
Support for partial play/weighting/player performance

### ISSUE THREAD

**Issue by spookybear0** [OpenDebates/openskill.py#29]
Would it be possible to add some sort of system to weight player performance like how the [official trueskill module does it](https://trueskill.org/#partial-play)? I'm trying to create a system that weights players overall performance compared to their teams to get a more accurate skill rating.

**Comment by daegontaven** [comment]
Referencing the original problem: https://github.com/philihp/openskill.js/issues/179#issuecomment-883596548. In short I am willing to create this feature if you can find matches with partial play.

**Comment by spookybear0** [comment]
Hmm, the use case I'm looking at is supporting player performance: for example

9-3

team 1: 9 goals

player 1: 7 goals = contributed 77%
player 2: 2 goals = contributed 23%

team 2: 3 goals

player 1: 2 goals = contributed 66%
player 2: 1 goal = contributed 33%

Of course there would be more factors to determine an MVP score sort of, but I'm wondering if its possible to weight skill rating gained/losted depending on how much was contributed to the team, ex: person with the most goals gains more on the winning team, and on the losing team, loses more.

**Comment by spookybear0** [comment]
In short: the use case for this would be to gauge player performance and weight it accordingly depending on how much was contributed to the team: in turn making the skill rating more accurate.

**Comment by Noxville** [comment]
# of goals seems like a poor example metric for partial play because, depending on the sport, specific positions are more likely to contribute to those specific scoring actions. Partial play in Trueskill is normally just used as a weighting for what % of the game you're active in.

**Comment by spookybear0** [comment]
As you can see in my other comment, the propsed use for this would use a calculated mvp point system.

**Comment by philihp** [comment]
> In short I am willing to create this feature if you can find data on matches with partial play.

Yep! Adding in this feature could be overfitting the model, and we have no way of knowing it without some data to benchmark it.

**Comment by spookybear0** [comment]
Ah, I see, I will come back with some data soon.
