### ISSUE TITLE
Unable to install on Google Colab

### ISSUE THREAD

**Issue by toshi71** [OpenDebates/openskill.py#51]
**Describe the bug**
I can't install openskill on Google Colab via pip.
What should I do?

**Screenshots**
![スクリーンショット 2022-03-31 23 14 18](https://user-images.githubusercontent.com/10680760/161076615-f509ebb6-6875-411e-ad29-90242982e1d8.png)

**Platform Information**
 - Google Colab
 - Python Version: 3.7.13

**Comment by daegontaven** [comment]
openskill currently only supports Python 3.10 and above.

**Comment by toshi71** [comment]
@daegontaven thanx a lot
