### ISSUE TITLE
Improve win predictions for 1v1 teams

### ISSUE THREAD

**Issue by nthypes** [OpenDebates/openskill.py#53]
First of all, congrats and thanks for the great repo!

In a scenario that **Player A** has 2x the rating of **Player B**, the predicted win probability is **_60%_** vs **_40%_**. This seems strange.

```
players = [ [Rating(50)], [Rating(25)] ]

predict_win(teams=players)

[ 1 ]: [0.6002914159316424, 0.39970858406835763]

```

If I use [this](https://github.com/sublee/trueskill/issues/1#issuecomment-149762508) function implementation, I get **_97%_** vs **_3%_** which sounds more reasonable to me.

Maybe the `predict_win` function has some flaw?

**Comment by daegontaven** [comment]
@nthypes This seems to be side effect of that function being generalized by us to accommodate for more than 2 teams. I just tested that function with openskill benchmarks and it does seem to perform better (by around 2%) on 1v1 teams. But overall it doesn't seem to affect the benchmarks by much. We actually created our benchmarks against the `win_probability` function proposed in that thread to compare against trueskill. As expected the ratings will get more accurate the lower sigma gets. If that 2% matters to you, feel free to create a pull request to add it as a special case for 1v1 teams.
